In [2]:
#import dependencies
import os
import csv
import pandas as pd

In [3]:
#read in the csv file
pride_2023=pd.read_csv('pride_2023.csv')
pride_2023.head()

C:\Users\hbour\AppData\Local\Temp\ipykernel_22484\3698653594.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  pride_2023=pd.read_csv('pride_2023.csv')

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,85C25D752209BE10,classic_bike,2023-06-25 15:34:56.514,2023-06-25 15:41:52.901,E 40 St & Park Ave,6432.11,W 52 St & 5 Ave,6700.01,40.750756,-73.978326,40.759923,-73.976485,member
1,D2443436DDD8A295,classic_bike,2023-06-25 16:05:46.616,2023-06-25 17:05:03.455,Pleasant Ave & E 116 St,7450.05,28 St & 41 Ave,6462.19,40.794988,-73.933335,40.751047,-73.937970,member
2,C74FC11925E2666F,classic_bike,2023-06-25 17:59:16.287,2023-06-25 18:02:32.612,Lenox Ave & W 117 St,7655.22,Frederick Douglass Blvd & W 115 St,7658.13,40.802557,-73.949078,40.803865,-73.955931,member
3,48ACB7A1BA2EE3AE,electric_bike,2023-06-25 19:27:02.819,2023-06-25 20:05:57.900,Morris Ave & E 171 St,8209.01,College Ave & E 169 St,8141.05,40.839052,-73.910796,40.835123,-73.911968,member
4,F0DC537A7FDACA73,electric_bike,2023-06-24 12:50:28.669,2023-06-24 13:44:20.180,W 54 St & 9 Ave,6920.03,E 40 St & Park Ave,6432.11,40.765837,-73.986900,40.750756,-73.978326,casual

In [5]:
#convert the csv file to a dataframe
pride_2023_df=pd.DataFrame(pride_2023)

#convert started_at and ended_at to datetime
pride_2023_df['started_at'] = pd.to_datetime(pride_2023_df['started_at'])
pride_2023_df['ended_at'] = pd.to_datetime(pride_2023_df['ended_at'])

In [6]:
#split the started_at and ended_at columns into date and time
pride_2023_df['start_date'] = pride_2023_df['started_at'].dt.date
pride_2023_df['start_time'] = pride_2023_df['started_at'].dt.time
pride_2023_df['end_date'] = pride_2023_df['ended_at'].dt.date
pride_2023_df['end_time'] = pride_2023_df['ended_at'].dt.time

#drop the started_at and ended_at columns
pride_2023_df=pride_2023_df.drop(columns=['started_at','ended_at'])

In [ ]:
#create a new column for the duration of the event
pride_2023_df['duration'] = (pd.to_datetime(pride_2023_df['end_time'].astype(str)) - pd.to_datetime(pride_2023_df['start_time'].astype(str)))

#convert the duration to minutes
pride_2023_df['duration'] = pride_2023_df['duration'].dt.total_seconds()/60

#convert the duration to an integer
pride_2023_df['duration'] = pride_2023_df['duration'].astype(int)

C:\Users\hbour\AppData\Local\Temp\ipykernel_22484\3923818021.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pride_2023_df['duration'] = (pd.to_datetime(pride_2023_df['end_time'].astype(str)) - pd.to_datetime(pride_2023_df['start_time'].astype(str)))
C:\Users\hbour\AppData\Local\Temp\ipykernel_22484\3923818021.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pride_2023_df['duration'] = (pd.to_datetime(pride_2023_df['end_time'].astype(str)) - pd.to_datetime(pride_2023_df['start_time'].astype(str)))

In [9]:
#display the dataframe
pride_2023_df.head()

,ride_id,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time,duration
0,85C25D752209BE10,classic_bike,E 40 St & Park Ave,6432.11,W 52 St & 5 Ave,6700.01,40.750756,-73.978326,40.759923,-73.976485,member,2023-06-25,15:34:56.514000,2023-06-25,15:41:52.901000,6
1,D2443436DDD8A295,classic_bike,Pleasant Ave & E 116 St,7450.05,28 St & 41 Ave,6462.19,40.794988,-73.933335,40.751047,-73.937970,member,2023-06-25,16:05:46.616000,2023-06-25,17:05:03.455000,59
2,C74FC11925E2666F,classic_bike,Lenox Ave & W 117 St,7655.22,Frederick Douglass Blvd & W 115 St,7658.13,40.802557,-73.949078,40.803865,-73.955931,member,2023-06-25,17:59:16.287000,2023-06-25,18:02:32.612000,3
3,48ACB7A1BA2EE3AE,electric_bike,Morris Ave & E 171 St,8209.01,College Ave & E 169 St,8141.05,40.839052,-73.910796,40.835123,-73.911968,member,2023-06-25,19:27:02.819000,2023-06-25,20:05:57.900000,38
4,F0DC537A7FDACA73,electric_bike,W 54 St & 9 Ave,6920.03,E 40 St & Park Ave,6432.11,40.765837,-73.986900,40.750756,-73.978326,casual,2023-06-24,12:50:28.669000,2023-06-24,13:44:20.180000,53

In [10]:
#change the name of the * values in the rideable_type column to "next_gen"
pride_2023_df['rideable_type'] = pride_2023_df['rideable_type'].replace(['*'],'next_gen')

#display the dataframe
pride_2023_df.head()

,ride_id,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time,duration
0,85C25D752209BE10,classic_bike,E 40 St & Park Ave,6432.11,W 52 St & 5 Ave,6700.01,40.750756,-73.978326,40.759923,-73.976485,member,2023-06-25,15:34:56.514000,2023-06-25,15:41:52.901000,6
1,D2443436DDD8A295,classic_bike,Pleasant Ave & E 116 St,7450.05,28 St & 41 Ave,6462.19,40.794988,-73.933335,40.751047,-73.937970,member,2023-06-25,16:05:46.616000,2023-06-25,17:05:03.455000,59
2,C74FC11925E2666F,classic_bike,Lenox Ave & W 117 St,7655.22,Frederick Douglass Blvd & W 115 St,7658.13,40.802557,-73.949078,40.803865,-73.955931,member,2023-06-25,17:59:16.287000,2023-06-25,18:02:32.612000,3
3,48ACB7A1BA2EE3AE,electric_bike,Morris Ave & E 171 St,8209.01,College Ave & E 169 St,8141.05,40.839052,-73.910796,40.835123,-73.911968,member,2023-06-25,19:27:02.819000,2023-06-25,20:05:57.900000,38
4,F0DC537A7FDACA73,electric_bike,W 54 St & 9 Ave,6920.03,E 40 St & Park Ave,6432.11,40.765837,-73.986900,40.750756,-73.978326,casual,2023-06-24,12:50:28.669000,2023-06-24,13:44:20.180000,53

In [14]:
#drop unnecessary columns
pride_2023_df=pride_2023_df.drop(columns=['start_lat', 'start_lng', 'end_lat', 'end_lng'])

In [15]:
#export the dataframe to a new csv file
pride_2023_df.to_csv('pride_2023_duration.csv', index=False)